name: Release Server(HG)

on:
  workflow_dispatch:
    inputs:
      repository_url:
        required: true
        default: 'apache/hugegraph'
      repository_branch:
        required: true
        default: 'release-1.5.0'
      release_version:
        required: true
        default: '1.5.0'
      deploy_maven:
        required: true
        type: boolean
        description: publish to maven nexus
        default: false
      deploy_svn:
        required: true
        type: boolean
        description: publish to apache svn
        default: false
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
       
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository_url }}
          ref: ${{ inputs.repository_branch }}
          fetch-depth: 2

      # - name: Cache Maven packages
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.m2/repository
      #     key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: ${{ runner.os }}-m2
          
      - name: Replace maven settings
        run: mkdir -p ~/.m2 && echo '${{ secrets.M2_SETTINGS }}' > ~/.m2/settings.xml

      - name: Package/Install Only
        if: ${{ !inputs.deploy_maven }}
        run: |
          (echo "just building" && mvn clean install -Papache-release,stage -DskipTests -e) || exit

      - name: Package & Release to maven
        if: ${{ inputs.deploy_maven }}
        run: |
          echo "deploy to maven" && mvn clean deploy -Papache-release,stage -DskipTests -e || exit 

      - name: Check consistency
        run: |
          md5sum hugegraph-server/apache-hugegraph-incubating-${{ inputs.release_version }}/lib/hugegraph-com*
          md5sum ~/.m2/repository/org/apache/hugegraph/hugegraph-common/${{ inputs.release_version }}/*.jar
          curl https://repository.apache.org/content/groups/staging/org/apache/hugegraph/hugegraph-common/${{ inputs.release_version }}/hugegraph-common-${{ inputs.release_version }}.jar.md5
        
        
      - name: Release to svn
        if: ${{ inputs.deploy_svn }}
        run: hugegraph-server/hugegraph-dist/scripts/apache-release.sh ${{ inputs.release_version }} ${{ secrets.RELEASE_USERNAME }} ${{ secrets.RELEASE_PASSWORD }}
